# Generated by Django 5.0.6 on 2024-08-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phonenumber",
            old_name="sent",
            new_name="sent_at",
        ),
    ]
