# Generated by Django 5.0.6 on 2024-08-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_sent_phonenumber_sent_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phonenumber",
            old_name="Phone_Number",
            new_name="phone_number",
        ),
    ]
